### ISSUE TITLE
Error en la eliminación de países

### ISSUE THREAD

**Issue by juan-tamarit** [juan-tamarit/PaisesPOO#18]
Encontramos que cuando desaparece un país en lugar de quitarlo y continuar salta el siguiente error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "e:\PC\programas\python\PaisesPOO\CPais.py", line 189, in <lambda>
    root.after(1000,lambda: self.ronda(Dado,root))
                            ^^^^^^^^^^^^^^^^^^^^^
  File "e:\PC\programas\python\PaisesPOO\CPais.py", line 188, in ronda
    self.limpia()
  File "e:\PC\programas\python\PaisesPOO\CPais.py", line 152, in limpia
    self.remove_pais(pais)
  File "e:\PC\programas\python\PaisesPOO\CPais.py", line 101, in remove_pais
    self.paises.remove(IPais)
ValueError: list.remove(x): x not in list

**Comment by juan-tamarit** [comment]
El problema se encuentra en el método remove_pais, cuando creamos la interfaces por error confundí un "Pais" que se pasa como parámetro con un objeto y lo cambié con un "IPais":

def remove_pais(self, Pais):
        self.paises.remove(IPais)

Se ha arreglado el problema:

def remove_pais(self, Pais):
        self.paises.remove(Pais)

He podido confirmar que se soluciona el problema
